name: stability
description: Stability AI dart package. Includes all the necessary tools to work with the Stability AI API. All endpoints implemented.
version: 0.0.2
repository: https://github.com/Mehmetyaz/stability
homepage: https://github.com/Mehmetyaz/stability

environment:
  sdk: ^3.5.0

dependencies:
  http: ^1.2.2

dev_dependencies:
  lints: ^4.0.0
  test: ^1.25.8
