name: stability
description: Stability AI dart package. Internal http implementation. No external dependencies.
version: 1.0.0
repository: https://github.com/Mehmetyaz/stability
homepage: https://github.com/Mehmetyaz/stability

environment:
  sdk: ^3.4.3

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.25.8
